# https://taskfile.dev

version: '3'

vars:
  STDARGS: -vet -strict-style -show-timings

interval: 500ms

tasks:
  default:
    cmds:
      - odin run . -o:minimal {{.STDARGS}}
    aliases: [run]
    
  build:
    cmds:
      - odin build . -o:minimal {{.STDARGS}}
  
  debug:
    cmds:
      - odin run . -debug -o:none -use-separate-modules {{.STDARGS}}

  debug_build:
    cmds:
      - odin build . -debug -o:none -use-separate-modules

  leaks:
    deps: [debug_build]
    cmds:
      - valgrind --leak-check=yes ./pxlwolf_odin

  test:
    watch: true
    sources:
      - '**/*.odin'
    cmds:
      - odin test .
    silent: true
