# https://taskfile.dev

version: '3'

vars:
  STDARGS: -vet -strict-style -show-timings -out:pxlwolf_odin

interval: 500ms

tasks:
  default:
    cmds:
      - odin run src/. -o:minimal {{.STDARGS}}
    aliases: [run]
    
  build:
    cmds:
      - odin build src/. -o:minimal {{.STDARGS}}
  
  debug:
    cmds:
      - odin run src/. -debug -o:none -use-separate-modules {{.STDARGS}}

  debug_build:
    cmds:
      - odin build src/. -debug -o:none -use-separate-modules

  leaks:
    deps: [debug_build]
    cmds:
      - valgrind --leak-check=yes ./pxlwolf_odin

  test:
    watch: true
    sources:
      - 'src/**/*.odin'
    cmds:
      - odin test src/.
    silent: true
